name: jaxili
dependencies:
  - python=3.10
  - pip
  - pip:
    - jupyter
    - matplotlib
    - numpy
    - numpydoc
    - jax
    - cmake
    - tensorflow_probability
    - optax
    - flax
    - sbibm
    - torch
    - optuna

