name: CD

on:
  push:
    branches:
      - main
  
jobs:
  docs:
    name: Deploy API Documentation
    runs-on: ubuntu-latest

  steps:
    - name: Install dependencies
      run: python -m pip install myst-parser numpy numpydoc sphinx

    - name: Build API documentation
      run: |
        sphinx-apidoc -Mfeo docs/source jaxili
        sphinx-build docs/source docs/build
      
    - name: Deploy API documentation
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
    