name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test-full:
    name: Run CI Tests
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: python -m pip install ".[lint, test]"
      
      - name: Run tests
        run: python -m pytest

      - name: Run linting tests
        run: |
          black --check .